language: python
python:
    - "3.8"
    - "3.6"
    - "3.4"
    - "2.7"

os:
    - linux

install:
  - pip install --upgrade pip
  - pip install pytest 
  - pip install pytest-cov==2.5.0
  - python setup.py install
  - pip install coveralls 

script: 
    - pytest --cov=ankivim

after_success:
    - coveralls
